### ISSUE TITLE
Checkbox: Cannot specify "checked" declaratively

### ISSUE THREAD

**Issue by mythic2** [ibm-js/deliteful#431] opened 2014-12-16 07:42 UTC
When I define a checkbox like this (following documentation/comments):

```html
<d-checkbox attach-point="cbSave" checked="true"></d-checkbox>
```

The checkbox control appears not to be checked (marker is missing).

It works fine to set checked programatically:

```js
this.cbSave.checked = true;
```

**Comment by cjolif** [comment] 2015-01-05 09:13
@mythic2 it seems we can't reproduce, can you provide a complete reproducing sample otherwise we will have to close this issue.

**Comment by mythic2** [comment] 2015-01-05 11:10
After looking into delite code, I can see my problem: I fetch templates from database and use ```handlebars.compile``` function which does not support ```requires=``` attribute (it is supported only in ```handlebars.load```)

So I have to require "deliteful/Checkbox" in advance, but code is somewhat fragile as it might depend on order of modules loaded etc. 

BTW the new error message "d-checkbox is not defined, do you miss requires="..." was pretty helpful even though it is misleading in this case.

**Comment by cjolif** [comment] 2015-01-05 11:47
ok thanks @mythic2 I guess we can close that one then.

**Closed by cjolif** 2015-01-05 11:47 UTC

**Comment by wkeese** [comment] 2015-01-05 12:28
@mythic2 - Perhaps it would help if the handlebars module had a `compileAsync()` method that processed the `requires` attribute (if there is one) and returns a promise for the template?

**Comment by mythic2** [comment] 2015-01-05 13:11
@wkeese I am sure that it would be quite helpful in cases where template is not downloaded through ```require``` function. 

However, it still requires the ```requires``` attribute. * cough * I would,probably,  welcome configuration option for handlesbar to define mapping 'd-checkbox' -> 'deliteful/Checkbox' so I have to configure mapping only once. 

(I am developing a rather complex application where templates will be created by a non core developers. So the simpler, the better. However, I understand I am not be primary target audience for the delite/deliteful.)

**Comment by wkeese** [comment] 2015-01-05 14:01
I see, yes that would be a nice enhancement too.  Perhaps an API like:

```js
require.config({
	config: {
		"delite/handlebars": {
			requires: {
                             "d-checkbox": "deliteful/Checkbox"
		}
	}
}
```

Anyway, I'll make the `compileAsync()` method.  I probably won't have time for the other thing but if you want to submit a PR for it that would be great.

**Comment by mythic2** [comment] 2015-01-05 14:12
That would be perfect! However before I make any PR, I have to solve out Dojo CLA with my company :-/
