### ISSUE TITLE
Dijit templates missing from build layer

### ISSUE THREAD

**Issue by kgibb** [ibm-js/deliteful#560] opened 2015-05-01 08:19 UTC
Dijit templates are not getting inlined during the build process. My project contains some custom dojo widgets. The JS gets included in the layer and the CSS is loaded via the requirejs-dplugins/css plugin so it gets included into layer.css. However the templates do not get included. I can manually append the templates to the layer and modify dojo/text but it's hacky. Any ideas? I don't want to rewrite these controls.

**Comment by wkeese** [comment] 2015-05-01 08:29
Did you really mean to type "dijit"?   You have a project that combines dijit and deliteful?

If so, it sounds like you should file a ticket against whatever build system you are using.  Is it grunt-amd-build in ibm-js?

**Comment by wkeese** [comment] 2015-05-01 08:42
PS: Probably though the problem is [dojo/text](https://github.com/dojo/dojo/blob/master/text.js), since AFAICT it's not written to spec.  It doesn't have a [`write()`](http://requirejs.org/docs/plugins.html#apiwrite) method.

It sounds like you have a hacky workaround already.  Another idea is to [map](http://requirejs.org/docs/api.html#config-map) dojo/text to the standard requirejs-text/text.  I haven't tried that though; not sure if the builder is smart enough to understand the remap.

**Comment by kgibb** [comment] 2015-05-01 08:45
Yes, our new project will be using deliteful but were hoping to migrate some of our custom controls, which were built using dijit controls (DateTextBox etc). Building with grunt-amd-build.

I'll try the map idea, thanks!

**Comment by kgibb** [comment] 2015-05-01 09:17
Mapping to requirejs-text/text worked, thanks!

**Comment by wkeese** [comment] 2015-05-01 09:57
OK great.  I filed https://bugs.dojotoolkit.org/ticket/18584 about the root issue.   I'm going to close this.

cc @clmath

**Closed by wkeese** 2015-05-01 09:57 UTC
