### ISSUE TITLE
Combobox: cannot set "class" attribute

### ISSUE THREAD

**Issue by mythic2** [ibm-js/deliteful#587] opened 2015-12-30 09:34 UTC
It is not possible to style the d-combobox element using css classes. Following example, does not set the desired class "fill" class on the element:
```
<d-combobox class="fill"></d-combobox>
```

The problem is in the Combobox.html template that is defined as
```
<template class="d-combobox" role="presentation" attach-point="buttonNode">
...
```
and the class attribute defined here overrides the desired value when ```deliver()``` method is called.

**Comment by wkeese** [comment] 2015-12-30 10:39
I suppose rather than having `class="d-combobox"` in the template that Combobox.js should set `baseClass`.

**Comment by AdrianVasiliu** [comment] 2015-12-30 10:50
The same would then hold for other widgets which also set `class` in their template (Switch, Checkbox...).

**Comment by wkeese** [comment] 2015-12-30 13:16
Right.   To be honest I thought setting it in the template also worked.   Because Template.js has this code:

```js
// Special path for class to not overwrite classes set by application or by other code.
this.buildText.push("this.setClassComponent('template', " + js + ", " + nodeName + ");");
this.generateWatchCode(dependsOn,
		"this.setClassComponent('template', " + js + ", " + nodeName + ")");
```

Not sure why that isn't working for Combobox.

**Comment by AdrianVasiliu** [comment] 2015-12-30 13:24
Ok, so I guess it would be better to first understand that before deciding how to fix it for all widgets having the problem. Not sure when I'll have a bit of time to look into it, though.

**Comment by wkeese** [comment] 2016-01-03 12:33
I tested `<d-combobox class="fill"></d-combobox>` by modifying samples/Combobox.html, and it works fine for me.  @mythic2, do you have a test case that reproduces the problem?

I also noticed that Combbox.js already sets `baseClass`, so the template shouldn't be setting `class=d-combobox`... but I just can't reproduce the problem you describe.

**Comment by mythic2** [comment] 2016-01-04 07:44
I use handlebars to process a template, which is generated on the fly:
```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="html5/libs/requirejs/require.js"></script>

    <script type="text/javascript">
        require.config({
            baseUrl: "html5/libs"
        });

        require([
            'delite/handlebars',
            "delite/register",
            "delite/Widget",
            "deliteful/Combobox",
            "requirejs-domready/domReady!"
        ], function(handlebars, register, Widget){
            register("test-app", [HTMLElement, Widget], {
                attachedCallback: function() {
                    var templateText = '<template><d-combobox class="fill"></d-combobox></template>';

                    handlebars.requireAndCompile(templateText, require).then(function (template) {
                        this.template = template;

                    }.bind(this))
                }
            });

            register.parse();
        });
    </script>
</head>

<body >
    <test-app id="test"></test-app>
</body>
</html>
```

**Comment by wkeese** [comment] 2016-01-08 05:23
OK thanks.  BTW you don't need to call `requireAndCompile()` unless your templates specifies additional requires.  In your case "test-app" can be defined as:

```#!js
register("test-app", [HTMLElement, Widget], {
	template: handlebars.compile('<template><d-combobox class="fill"></d-combobox></template>')
});
```

It still hits the same bug though.

**Comment by wkeese** [comment] 2016-01-08 06:10
(Note to self...)  If you call `new Combobox({"class": "fill"})` from your application, register.js calls `.setClassComponent("user", "fill")` and Template.js calls `.setClassComponent("template", "d-combobox")`, and the `d-combobox` node ends up with the two classes.

But if you have `<d-combobox class=fill>` *in a template*, Template.js calls `.setClassComponent("template", "fill")` when creating the `test-app` widget, and `.setClassComponent("template", "d-combobox")` when creating the `d-combobox` widget.

The problem is that `.setClassComponent()` is dependent on each piece of code specifying a unique first argument.

I will work on a solution.

**Comment by wkeese** [comment] 2016-01-08 07:35
Closing this in favor of ibm-js/delite#434 and #588.

**Closed by wkeese** 2016-01-08 07:35 UTC
